"""Generate platform styles from the reviewed cross-client design tokens."""

from __future__ import annotations

import argparse
import json
import re
import sys
from copy import deepcopy
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
TOKEN_PATH = PROJECT_ROOT / "frontend" / "design-tokens.json"
WEB_OUTPUT = PROJECT_ROOT / "web" / "design-tokens.css"
MINIAPP_OUTPUT = PROJECT_ROOT / "miniapp" / "styles" / "design-tokens.wxss"
MINIAPP_CONFIG = PROJECT_ROOT / "miniapp" / "app.json"
TOKEN_NAME = re.compile(r"^[a-z][a-z0-9-]*$")
HEX_COLOR = re.compile(r"^#[0-9a-f]{6}$")


def load_colors() -> dict[str, str]:
    document = json.loads(TOKEN_PATH.read_text(encoding="utf-8"))
    if document.get("schema_version") != 1 or not isinstance(document.get("colors"), dict):
        raise ValueError("design-tokens.json must contain schema_version 1 and a colors object")

    colors: dict[str, str] = {}
    for name, value in document["colors"].items():
        if not isinstance(name, str) or not TOKEN_NAME.fullmatch(name):
            raise ValueError(f"Invalid design-token name: {name}")
        if not isinstance(value, str) or not HEX_COLOR.fullmatch(value):
            raise ValueError(f"Design token {name} must be a lowercase six-digit hex color")
        colors[name] = value
    return colors


def stylesheet(selector: str, colors: dict[str, str]) -> str:
    lines = [
        "/* Generated by scripts/generate_design_tokens.py; edit frontend/design-tokens.json. */",
        f"{selector} {{",
        *(f"  --{name}: {value};" for name, value in colors.items()),
        "}",
        "",
    ]
    return "\n".join(lines)


def miniapp_config(colors: dict[str, str]) -> str:
    config = deepcopy(json.loads(MINIAPP_CONFIG.read_text(encoding="utf-8")))
    config["window"]["navigationBarBackgroundColor"] = colors["navy"]
    config["window"]["backgroundColor"] = colors["canvas"]
    config["tabBar"]["color"] = colors["muted"]
    config["tabBar"]["selectedColor"] = colors["green"]
    return json.dumps(config, ensure_ascii=False, indent=2) + "\n"


def expected_outputs() -> dict[Path, str]:
    colors = load_colors()
    return {
        WEB_OUTPUT: stylesheet(":root", colors),
        MINIAPP_OUTPUT: stylesheet("page", colors),
        MINIAPP_CONFIG: miniapp_config(colors),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Finance Agent cross-client design tokens.")
    parser.add_argument("--check", action="store_true", help="Fail if committed outputs differ from the token source.")
    arguments = parser.parse_args()

    outputs = expected_outputs()
    if arguments.check:
        stale = [path for path, content in outputs.items() if not path.is_file() or path.read_text("utf-8") != content]
        if stale:
            print("Generated design-token outputs are stale:", file=sys.stderr)
            for path in stale:
                print(f"- {path.relative_to(PROJECT_ROOT)}", file=sys.stderr)
            raise SystemExit(1)
        print("Design-token outputs are current")
        return

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"Updated {path.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
