apiVersion: v1
kind: Service
metadata:
  name: finance-agent
  namespace: finance-agent-staging
  labels:
    app.kubernetes.io/name: finance-agent
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: finance-agent
    app.kubernetes.io/environment: staging
  ports:
    - name: http
      port: 8000
      targetPort: http
      nodePort: 30080
      protocol: TCP
