"""Market-data adapters available to the financial research agent."""

from .alltick import (
    FREE_PLAN_LIMITS,
    AllTickApiError,
    AllTickAssetClass,
    AllTickCandle,
    AllTickClient,
    AllTickKlineType,
    AllTickQuote,
    AllTickRateLimitError,
)
from .biying import BiyingClient, BiyingQuote, BiyingStock
from .aktools import (
    DEFAULT_AKTOOLS_BASE_URL,
    AkToolsApiError,
    AkToolsCandle,
    AkToolsClient,
    AkToolsError,
    AkToolsRateLimitError,
    AkToolsServiceVersion,
    AkToolsTransportError,
)
from .baostock import (
    BAOSTOCK_DAILY_IP_LIMIT,
    DEFAULT_BAOSTOCK_LIMITS,
    BaoStockApiError,
    BaoStockCandle,
    BaoStockClient,
    BaoStockDependencyError,
    BaoStockError,
    BaoStockRateLimitError,
    BaoStockSessionError,
)

__all__ = [
    "FREE_PLAN_LIMITS",
    "AllTickApiError",
    "AllTickAssetClass",
    "AllTickCandle",
    "AllTickClient",
    "AllTickKlineType",
    "AllTickQuote",
    "AllTickRateLimitError",
    "BiyingClient",
    "BiyingQuote",
    "BiyingStock",
    "DEFAULT_AKTOOLS_BASE_URL",
    "AkToolsApiError",
    "AkToolsCandle",
    "AkToolsClient",
    "AkToolsError",
    "AkToolsRateLimitError",
    "AkToolsServiceVersion",
    "AkToolsTransportError",
    "BAOSTOCK_DAILY_IP_LIMIT",
    "DEFAULT_BAOSTOCK_LIMITS",
    "BaoStockApiError",
    "BaoStockCandle",
    "BaoStockClient",
    "BaoStockDependencyError",
    "BaoStockError",
    "BaoStockRateLimitError",
    "BaoStockSessionError",
]
