"""Market-data adapters available to the financial research agent."""

from .alltick import (
    FREE_PLAN_LIMITS,
    AllTickApiError,
    AllTickAssetClass,
    AllTickCandle,
    AllTickClient,
    AllTickKlineType,
    AllTickQuote,
    AllTickRateLimitError,
)
from .alphavantage import (
    ALPHAVANTAGE_API_BASE,
    FREE_PLAN_LIMITS as ALPHAVANTAGE_FREE_PLAN_LIMITS,
    AlphaVantageApiError,
    AlphaVantageCandle,
    AlphaVantageClient,
    AlphaVantageError,
    AlphaVantageLimits,
    AlphaVantageQuote,
    AlphaVantageRateLimitError,
    AlphaVantageSymbol,
    AlphaVantageTransportError,
)
from .eodhd import (
    EODHD_API_BASE,
    FREE_PLAN_LIMITS as EODHD_FREE_PLAN_LIMITS,
    EODHDApiError,
    EODHDCandle,
    EODHDClient,
    EODHDError,
    EODHDLimits,
    EODHDRateLimitError,
    EODHDSearchMatch,
    EODHDTransportError,
)
from .biying import BiyingClient, BiyingQuote, BiyingStock
from .aktools import (
    DEFAULT_AKTOOLS_BASE_URL,
    AkToolsApiError,
    AkToolsCandle,
    AkToolsClient,
    AkToolsError,
    AkToolsRateLimitError,
    AkToolsServiceVersion,
    AkToolsTransportError,
)
from .baostock import (
    BAOSTOCK_DAILY_IP_LIMIT,
    DEFAULT_BAOSTOCK_LIMITS,
    BaoStockApiError,
    BaoStockCandle,
    BaoStockClient,
    BaoStockDependencyError,
    BaoStockError,
    BaoStockRateLimitError,
    BaoStockSessionError,
)
from .yfinance import (
    DEFAULT_YFINANCE_LIMITS,
    YFinanceApiError,
    YFinanceCandle,
    YFinanceClient,
    YFinanceDependencyError,
    YFinanceError,
    YFinanceRateLimitError,
    YFinanceTransportError,
)
from .zhitu import (
    DOCUMENTED_MINIMUM_PLAN_LIMITS as ZHITU_DOCUMENTED_MINIMUM_PLAN_LIMITS,
    ZHITU_API_BASE,
    ZhituApiError,
    ZhituCandle,
    ZhituClient,
    ZhituError,
    ZhituLimits,
    ZhituQuote,
    ZhituRateLimitError,
    ZhituTransportError,
)

__all__ = [
    "FREE_PLAN_LIMITS",
    "AllTickApiError",
    "AllTickAssetClass",
    "AllTickCandle",
    "AllTickClient",
    "AllTickKlineType",
    "AllTickQuote",
    "AllTickRateLimitError",
    "ALPHAVANTAGE_API_BASE",
    "ALPHAVANTAGE_FREE_PLAN_LIMITS",
    "AlphaVantageApiError",
    "AlphaVantageCandle",
    "AlphaVantageClient",
    "AlphaVantageError",
    "AlphaVantageLimits",
    "AlphaVantageQuote",
    "AlphaVantageRateLimitError",
    "AlphaVantageSymbol",
    "AlphaVantageTransportError",
    "EODHD_API_BASE",
    "EODHD_FREE_PLAN_LIMITS",
    "EODHDApiError",
    "EODHDCandle",
    "EODHDClient",
    "EODHDError",
    "EODHDLimits",
    "EODHDRateLimitError",
    "EODHDSearchMatch",
    "EODHDTransportError",
    "BiyingClient",
    "BiyingQuote",
    "BiyingStock",
    "DEFAULT_AKTOOLS_BASE_URL",
    "AkToolsApiError",
    "AkToolsCandle",
    "AkToolsClient",
    "AkToolsError",
    "AkToolsRateLimitError",
    "AkToolsServiceVersion",
    "AkToolsTransportError",
    "BAOSTOCK_DAILY_IP_LIMIT",
    "DEFAULT_BAOSTOCK_LIMITS",
    "BaoStockApiError",
    "BaoStockCandle",
    "BaoStockClient",
    "BaoStockDependencyError",
    "BaoStockError",
    "BaoStockRateLimitError",
    "BaoStockSessionError",
    "DEFAULT_YFINANCE_LIMITS",
    "YFinanceApiError",
    "YFinanceCandle",
    "YFinanceClient",
    "YFinanceDependencyError",
    "YFinanceError",
    "YFinanceRateLimitError",
    "YFinanceTransportError",
    "ZHITU_DOCUMENTED_MINIMUM_PLAN_LIMITS",
    "ZHITU_API_BASE",
    "ZhituApiError",
    "ZhituCandle",
    "ZhituClient",
    "ZhituError",
    "ZhituLimits",
    "ZhituQuote",
    "ZhituRateLimitError",
    "ZhituTransportError",
]
